on: 
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Your name'
        # Default value if no value is explicitly provided
        default: 'Github'
        # Input has to be provided for the workflow to run
        required: true
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to create (must start with a number, e.g. 0.1-rc1 or 0.2 - the v will be prepended!)'
        # Default value if no value is explicitly provided
        default: '0.0'
        # Input has to be provided for the workflow to run
        required: true
      message:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Message for release'
        # Default value if no value is explicitly provided
        default: 'For the most recent version and additional information, see https://social-science-data-editors.github.io/template_README/.'
        # Input has to be provided for the workflow to run
        required: true
      prerelease:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Is this a pre-release? (true/false)'
        # Default value if no value is explicitly provided
        default: 'false'
        type: choice
        options:
        - true
        - false 
      confirmation:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'This will also post to Zenodo - are you sure? (yes/no)'
        # Default value if no value is explicitly provided
        type: boolean
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ input.confirmation  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: release-candidate
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Template README in Social Sciences v${{ github.event.inputs.version }}
          body: |
            ${{ github.event.inputs.message }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}