on: 
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Your name'
        # Default value if no value is explicitly provided
        default: 'Github'
        # Input has to be provided for the workflow to run
        required: true
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to create (must start with a number, e.g. 0.1-rc1 or 0.2 - the v will be prepended!)'
        # Default value if no value is explicitly provided
        default: '0.0'
        # Input has to be provided for the workflow to run
        required: true
      message:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Message for release'
        # Default value if no value is explicitly provided
        default: 'For the most recent version and additional information, see https://social-science-data-editors.github.io/template_README/.'
        # Input has to be provided for the workflow to run
        required: true
      prerelease:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Is this a pre-release? (true/false)'
        # Default value if no value is explicitly provided
        default: 'false'
        type: choice
        options:
        - "true"
        - "false" 
      confirmation:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'This will also post to Zenodo - are you sure? '
        # Default value if no value is explicitly provided
        required: true
        type: boolean
name: Create Release

jobs:
  create-relase:
    name: Actually Create Release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    if: ${{ inputs.confirmation  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: release-candidate

      - name: Prepare tag
        id: prepare_tag
        run: |
          echo "vVERSION=v${{ inputs.version }}" >> "${GITHUB_OUTPUT}"
          cp CITATION.cff templates/

      - name: push files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          user_name: 'Github Action Bot'
          user_email: 'lars.vilhuber@cornell.edu'
          tag_name: ${{ steps.prepare_tag.outputs.vVERSION }}
          tag_message: 'Template README in Social Sciences ${{ steps.prepare_tag.outputs.vVERSION }}'
          publish_dir: templates/
          publish_branch: releases
          keep_files: false
          commit_message: 'Creating release ${{ steps.prepare_tag.outputs.vVERSION }}'
  