on: 
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Your name'
        # Default value if no value is explicitly provided
        default: 'Github'
        # Input has to be provided for the workflow to run
        required: true
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to create (must start with a number, e.g. 0.1-rc1 or 0.2 - the v will be prepended!)'
        # Default value if no value is explicitly provided
        default: '0.0'
        # Input has to be provided for the workflow to run
        required: true
      message:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Message for release'
        # Default value if no value is explicitly provided
        default: 'For the most recent version and additional information, see https://social-science-data-editors.github.io/template_README/.'
        # Input has to be provided for the workflow to run
        required: true
      prerelease:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Is this a pre-release? (true/false)'
        # Default value if no value is explicitly provided
        default: 'false'
        type: choice
        options:
        - "true"
        - "false" 
      confirmation:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'This will also post to Zenodo - are you sure? (yes/no)'
        # Default value if no value is explicitly provided
        type: boolean
name: Create Release

jobs:
  create-relase:
    name: Actually Create Release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    if: ${{ input.confirmation  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: release-candidate
      - name: push files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:  ${{ secrets.GITHUB_TOKEN }}
          user_name: 'Github Action Bot'
          user_email: 'lars.vilhuber@cornell.edu'
          publish_dir: templates
          publish_branch: releases
          keep_files: false
          commit_message: '[noaction] Creating release ${{ input.version }}'
  publish-pages:
    name: Publish release
    runs-on: ubuntu-latest
    if: ${{ input.confirmation  }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: releases
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: Template README in Social Sciences v${{ github.event.inputs.version }}
          body: |
            ${{ github.event.inputs.message }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}