# This is a basic workflow to help you get started with Actions

name: Pre-process files

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a  job called "build"
  convert_docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[noaction]')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Update ubuntu 
      run: sudo apt-get update
    - name: install wkhtml
      run: sudo apt-get install wkhtmltopdf xvfb
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Create directory
      run: "[[ -d templates ]] || mkdir templates "

    - name: Create temp directory
      run: "[[ -d temp ]] || mkdir temp "

    - name: Fix webroot
      run: _scripts/set_webroot.sh template-README.md _README.md
    - name: Add logo and footer
      run: _scripts/add-metadata.sh template-README.md _README.md cite

    # Create annotated README
    - name: Run docker for HTML 
      uses: docker://pandoc/latex:2.9
      with:
          args: "_README.md --standalone -t html5                          -o templates/README.html --metadata pagetitle=README --lua-filter=_scripts/links-to-html.lua"

    # Create sparse README
    - name: Create sparse README
      run: _scripts/sparsify.sh template-README.md _README_sparse.md
    - name: Add logo and footer
      run: _scripts/add-metadata.sh template-README.md _README.md based


    - name: Convert HTML to PDF (annotated)
      run: "/usr/bin/xvfb-run /usr/bin/wkhtmltopdf templates/README.html templates/README_annotated.pdf"
    # Runs a single command using the runners shell
    - name: Remove temp directory
      run: "rm -rf temp "
    # Convert to other formats
    - name: Run docker for Docx (annotated)
      uses: docker://pandoc/latex:2.9
      with:
          args: "_README.md --standalone -t docx                           -o templates/README_annotated.docx --lua-filter=_scripts/links-to-html.lua"
    - name: Run docker for Docx (sparse)
      uses: docker://pandoc/latex:2.9
      with:
          args: "_README_sparse.md --standalone -t docx                           -o templates/README.docx --lua-filter=_scripts/links-to-html.lua"
    - name: Run docker for latex (sparse)
      uses: docker://pandoc/latex:2.9
      with:
          args: "_README_sparse.md --standalone -t latex --template=default.latex -o templates/README.tex --lua-filter=_scripts/links-to-html.lua"
    - name: Move sparse to output folder
      run: "mv _README_sparse.md templates/README_sparse.md"
    - name: Set up git config
      run: |
          # setup the username and email. 
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    - name: Add and remove files
      run: |
        cp template-README.md templates/README.md
        git add templates/README*
        git commit -m "Adding derived files"
        git checkout -b release-candidate
        git push origin release-candidate --force
        