# This is a basic workflow to help you get started with Actions

name: Publish pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the specified branch
on:
  push:
    branches: 
      - release-candidate 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a  job called "build"
  publish-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: release-candidate
    - name: Add and remove files
      run: |
        rm -rf .github
        rm -rf _scripts
    - name: push files
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token:  ${{ secrets.GITHUB_TOKEN }}
         user_name: 'Github Action Bot'
         user_email: 'lars.vilhuber@cornell.edu'
         publish_dir: .
         publish_branch: gh-pages
         keep_files: false
         enable_jekyll: true
         commit_message: '[noaction] Updating web pages'

        
